---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-robotide
  failurePolicy: Fail
  name: mrobotide.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robotides
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-robotvdi
  failurePolicy: Fail
  name: mrobotvdi.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robotvdis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-workspacemanager
  failurePolicy: Fail
  name: mworkspacemanager.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspacemanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-buildmanager
  failurePolicy: Fail
  name: mbuildmanager.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buildmanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-launchmanager
  failurePolicy: Fail
  name: mlaunchmanager.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - launchmanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-metricscollector
  failurePolicy: Fail
  name: mmetricscollector.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metricscollectors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-robot
  failurePolicy: Fail
  name: mrobot.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robots
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-discoveryserver
  failurePolicy: Fail
  name: mdiscoveryserver.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - discoveryservers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-robotide
  failurePolicy: Fail
  name: vrobotide.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robotides
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-robotvdi
  failurePolicy: Fail
  name: vrobotvdi.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robotvdis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-workspacemanager
  failurePolicy: Fail
  name: vworkspacemanager.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspacemanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-buildmanager
  failurePolicy: Fail
  name: vbuildmanager.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buildmanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-launchmanager
  failurePolicy: Fail
  name: vlaunchmanager.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - launchmanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-metricscollector
  failurePolicy: Fail
  name: vmetricscollector.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metricscollectors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-robot
  failurePolicy: Fail
  name: vrobot.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robots
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-discoveryserver
  failurePolicy: Fail
  name: vdiscoveryserver.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - discoveryservers
  sideEffects: None
