# permissions for end users to view robotdevsuites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: robotdevsuite-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: robot-operator
    app.kubernetes.io/part-of: robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: robotdevsuite-viewer-role
rules:
- apiGroups:
  - dev.roboscale.io
  resources:
  - robotdevsuites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dev.roboscale.io
  resources:
  - robotdevsuites/status
  verbs:
  - get
