# permissions for end users to edit rosbridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rosbridge-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: robot-operator
    app.kubernetes.io/part-of: robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: rosbridge-editor-role
rules:
- apiGroups:
  - dev.roboscale.io
  resources:
  - rosbridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dev.roboscale.io
  resources:
  - rosbridges/status
  verbs:
  - get
